/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uema.uemesc;

import br.uema.uemesc.control.TabelaAtributosController;
import br.uema.uemesc.util.Operacoes;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lccf
 */
public class Pp extends javax.swing.JFrame {

    private DefaultListModel lstModel;
    private TabelaAtributosController tac;

    /**
     * Creates new form Dbf2Colors
     */
    public Pp() {
        initComponents();
        zeroStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShp = new javax.swing.JLabel();
        lblDbf = new javax.swing.JLabel();
        lblSld = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        txtShp = new javax.swing.JTextField();
        txtDbf = new javax.swing.JTextField();
        txtSld = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        pnlStatus = new javax.swing.JScrollPane();
        lstStatus = new javax.swing.JList<>();
        btnProcessar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uemesc Pre-processador .dbf + .sld");

        lblShp.setText("Arquivo .shp:");

        lblDbf.setText("Arquivo .dbf:");

        lblSld.setText("Arquivo .sld:");

        btnAbrir.setText("Abrir Projeto");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
        });

        lblStatus.setText("Status:");

        pnlStatus.setViewportView(lstStatus);

        btnProcessar.setText("Processar >>");
        btnProcessar.setEnabled(false);
        btnProcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcessarMouseClicked(evt);
            }
        });

        btnFechar.setText("X Fechar");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShp)
                            .addComponent(lblDbf)
                            .addComponent(lblSld))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDbf)
                            .addComponent(txtShp)
                            .addComponent(txtSld, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProcessar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFechar)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnProcessar)
                    .addComponent(btnFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShp)
                    .addComponent(txtShp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDbf)
                    .addComponent(txtDbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStatus(String text, int status) {
        int pos = lstStatus.getModel().getSize();
        String sts;
        switch (status) {
            case Operacoes.NAO_ENCONTRADO:
                sts = "Nfd: ";
                break;
            case Operacoes.ABERTO:
                sts = "Opn: ";
                break;
            case Operacoes.MENSAGEM:
                sts = "Msg: ";
                break;
            case Operacoes.SQL:
                sts = "Sql: ";
                break;
            default:
                sts = "Err: ";
        }
        lstModel.add(pos, sts + text);
    }
    
    private void zeroStatus(){
        this.lstModel = new DefaultListModel();
        lstStatus.setModel(lstModel);
    }
    
    private void op2Status() {
        tac.getOps().forEach((op) -> {
            addStatus(op.getOperacao(), op.getTipo());
        });
        tac.resetOps();
    }

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("ShapeFile", "shp");
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            lstModel.clear();
            File shpFile = fileChooser.getSelectedFile();
            String shpStr = shpFile.getAbsolutePath();
            String dbfStr = shpStr.replace(".shp", ".dbf");
            String sldStr = shpStr.replace(".shp", ".sld");
            File dbfFile = new File(dbfStr);
            File sldFile = new File(sldStr);
            txtShp.setText(shpStr);
            txtDbf.setText(dbfStr);
            txtSld.setText(sldStr);
            addStatus(shpStr, shpFile.exists() ? 1 : 0);
            addStatus(dbfStr, dbfFile.exists() ? 1 : 0);
            addStatus(sldStr, sldFile.exists() ? 1 : 0);
            if (dbfFile.exists() && sldFile.exists()) {
                try {
                    this.tac = new TabelaAtributosController(dbfFile, sldFile, 1);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(Pp.class.getName()).log(Level.SEVERE, null, ex);
                }
                btnProcessar.setEnabled(true);
            } else {
                btnProcessar.setEnabled(false);
                addStatus("Arquivo ausente!!!", Operacoes.ERRO);
            }
        }
        op2Status();
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnProcessarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessarMouseClicked
        // TODO add your handling code here:
        try {           
            tac.joinTabelaDados();
            btnProcessar.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Pp.class.getName()).log(Level.SEVERE, null, ex);
        }
        op2Status();
    }//GEN-LAST:event_btnProcessarMouseClicked

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JLabel lblDbf;
    private javax.swing.JLabel lblShp;
    private javax.swing.JLabel lblSld;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> lstStatus;
    private javax.swing.JScrollPane pnlStatus;
    private javax.swing.JTextField txtDbf;
    private javax.swing.JTextField txtShp;
    private javax.swing.JTextField txtSld;
    // End of variables declaration//GEN-END:variables
}
